openapi: 3.0.3
info:
  title: FairAir Authentication API
  description: Authentication endpoints for the FairAir booking platform
  version: 1.0.0
  contact:
    name: FairAir API Team

servers:
  - url: https://api.fairair.com/v1
    description: Production server
  - url: http://localhost:8080/v1
    description: Development server

paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticate user and return JWT tokens
      operationId: login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              email: "user@example.com"
              password: "securePassword123"
              deviceId: "device-abc-123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitResponse'
          headers:
            Retry-After:
              schema:
                type: integer
              description: Seconds until rate limit resets

  /auth/refresh:
    post:
      summary: Refresh access token
      description: Get new access token using refresh token
      operationId: refreshToken
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitResponse'

  /auth/logout:
    post:
      summary: User logout
      description: Revoke refresh token and invalidate session
      operationId: logout
      tags:
        - Authentication
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: Optional - revoke specific refresh token
                allDevices:
                  type: boolean
                  description: Revoke all tokens for user
                  default: false
      responses:
        '204':
          description: Logout successful
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/me:
    get:
      summary: Get current user
      description: Returns information about the currently authenticated user
      operationId: getCurrentUser
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token

  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          maxLength: 255
          description: User email address
          example: "user@example.com"
        password:
          type: string
          minLength: 8
          maxLength: 128
          description: User password
          example: "securePassword123"
        deviceId:
          type: string
          maxLength: 64
          pattern: '^[a-zA-Z0-9-_]+$'
          description: Optional device identifier for token binding
          example: "device-abc-123"

    LoginResponse:
      type: object
      required:
        - accessToken
        - refreshToken
        - expiresIn
        - refreshExpiresIn
        - tokenType
      properties:
        accessToken:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        refreshToken:
          type: string
          description: JWT refresh token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        expiresIn:
          type: integer
          format: int64
          description: Access token TTL in seconds
          example: 900
        refreshExpiresIn:
          type: integer
          format: int64
          description: Refresh token TTL in seconds
          example: 604800
        tokenType:
          type: string
          enum: [Bearer]
          description: Token type (always Bearer)
          example: "Bearer"

    TokenRefreshRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          description: Valid refresh token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    UserInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: User ID
        email:
          type: string
          format: email
          description: User email
        roles:
          type: array
          items:
            type: string
          description: User roles

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "invalid_credentials"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid email or password"
        details:
          type: object
          additionalProperties:
            type: string
          description: Additional error details

    RateLimitResponse:
      type: object
      required:
        - error
        - message
        - retryAfter
        - limit
        - remaining
        - resetAt
      properties:
        error:
          type: string
          default: "rate_limit_exceeded"
        message:
          type: string
          default: "Too many requests. Please try again later."
        retryAfter:
          type: integer
          format: int64
          description: Seconds until limit resets
        limit:
          type: integer
          format: int64
          description: Requests allowed per window
        remaining:
          type: integer
          format: int64
          description: Requests remaining in current window
        resetAt:
          type: integer
          format: int64
          description: Unix timestamp when window resets
