openapi: 3.0.3
info:
  title: FairAir Security Headers Specification
  description: Required HTTP security headers for all API responses
  version: 1.0.0

# This document specifies security headers that MUST be present
# on all API responses from the FairAir backend.

components:
  headers:
    # Prevents MIME type sniffing
    X-Content-Type-Options:
      description: Prevents browsers from MIME-sniffing the response
      schema:
        type: string
        enum: [nosniff]
      required: true
      example: nosniff

    # Prevents clickjacking
    X-Frame-Options:
      description: Prevents the page from being embedded in iframes
      schema:
        type: string
        enum: [DENY, SAMEORIGIN]
      required: true
      example: DENY

    # XSS protection (legacy, but still recommended)
    X-XSS-Protection:
      description: Enables browser XSS filtering
      schema:
        type: string
      required: true
      example: "1; mode=block"

    # HTTP Strict Transport Security
    Strict-Transport-Security:
      description: Forces HTTPS connections
      schema:
        type: string
      required: true
      example: "max-age=31536000; includeSubDomains"

    # Content Security Policy
    Content-Security-Policy:
      description: Restricts resource loading sources
      schema:
        type: string
      required: true
      example: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://api.fairair.com"

    # Referrer Policy
    Referrer-Policy:
      description: Controls referrer information in requests
      schema:
        type: string
        enum:
          - no-referrer
          - no-referrer-when-downgrade
          - origin
          - origin-when-cross-origin
          - same-origin
          - strict-origin
          - strict-origin-when-cross-origin
          - unsafe-url
      required: true
      example: strict-origin-when-cross-origin

    # Permissions Policy (formerly Feature-Policy)
    Permissions-Policy:
      description: Controls which browser features can be used
      schema:
        type: string
      required: true
      example: "geolocation=(), microphone=(), camera=()"

    # Rate Limit Headers
    X-RateLimit-Limit:
      description: Maximum requests allowed in window
      schema:
        type: integer
      required: false
      example: 100

    X-RateLimit-Remaining:
      description: Requests remaining in current window
      schema:
        type: integer
      required: false
      example: 95

    X-RateLimit-Reset:
      description: Unix timestamp when window resets
      schema:
        type: integer
        format: int64
      required: false
      example: 1701388800

    Retry-After:
      description: Seconds to wait before retrying (when rate limited)
      schema:
        type: integer
      required: false
      example: 60

# Example response with all required headers
x-response-example:
  headers:
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: "1; mode=block"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    Content-Security-Policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://api.fairair.com"
    Referrer-Policy: strict-origin-when-cross-origin
    Permissions-Policy: "geolocation=(), microphone=(), camera=()"
    X-RateLimit-Limit: 100
    X-RateLimit-Remaining: 95
    X-RateLimit-Reset: 1701388800

# Implementation Notes
x-implementation-notes:
  spring-webflux: |
    Implement as WebFilter:

    @Component
    class SecurityHeadersFilter : WebFilter {
        override fun filter(exchange: ServerWebExchange, chain: WebFilterChain): Mono<Void> {
            exchange.response.headers.apply {
                set("X-Content-Type-Options", "nosniff")
                set("X-Frame-Options", "DENY")
                set("X-XSS-Protection", "1; mode=block")
                set("Strict-Transport-Security", "max-age=31536000; includeSubDomains")
                set("Content-Security-Policy", "default-src 'self'; ...")
                set("Referrer-Policy", "strict-origin-when-cross-origin")
                set("Permissions-Policy", "geolocation=(), microphone=(), camera=()")
            }
            return chain.filter(exchange)
        }
    }

  csp-details: |
    Content-Security-Policy breakdown:
    - default-src 'self': Default to same-origin only
    - script-src 'self': Scripts from same origin
    - style-src 'self' 'unsafe-inline': Styles from same origin + inline (for Compose)
    - img-src 'self' data: https:: Images from same origin, data URIs, and HTTPS
    - font-src 'self': Fonts from same origin
    - connect-src 'self' https://api.fairair.com: XHR/fetch to same origin and API

  hsts-requirements: |
    HSTS Requirements:
    - max-age MUST be at least 31536000 (1 year)
    - includeSubDomains SHOULD be set
    - preload MAY be added after testing (requires HSTS preload list submission)

  cors-vs-csp: |
    Note: CORS and CSP serve different purposes:
    - CORS: Controls which origins can make requests TO our server
    - CSP: Controls which resources our pages can load FROM other servers
    Both are required for complete protection.
